apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: init-gogs-
spec:
  taskSpec:
    inputs:
      params:
        - name: GOGS_USER
          type: string
          description: Gogs admin username
          default: gogs
        - name: GOGS_PASSWORD
          type: string
          description: Gogs admin password
          default: gogs
        - name: REPO_TO_CLONE
          type: string
          description: The url of the REPO to copy into gogs.
          default: https://github.com/hatmarch/fraud_detection_support.git
    stepTemplate:
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
    steps:
      - name: init-gogs
        image: quay.io/siamaksade/python-oc
        script: |
          #!/usr/bin/env python3

          import os
          import requests 

          gogs_user = "$(inputs.params.GOGS_USER)"
          gogs_pwd = "$(inputs.params.GOGS_PASSWORD)"
          # FIXME: Webhook url could be the name of the svc with the port at the end
          webhookURL = "http://" + os.popen('oc get route webhook -o template --template="{{.spec.host}}"').read()
          gogsURL = "http://" + os.popen('oc get svc gogs -o template --template="{{.spec.clusterIP}}"').read() + ":3000"

          # create admin user
          data_user = {
          'user_name': gogs_user,
          'password': gogs_pwd,
          'retype': gogs_pwd,
          'email': 'admin@gogs.com'
          }

          resp = requests.post(url = gogsURL + "/user/sign_up", data = data_user) 

          if resp.status_code != 200:
            print("Error creating Gogs admin (status code: {})".format(resp.status_code))
            print(resp.content)
          else:
            print("Created admin user {}:{}".format(gogs_user, gogs_pwd))

          # create git repo
          data_repo = '{"clone_addr": "$(inputs.params.REPO_TO_CLONE)", "uid": 1, "repo_name": "fraud_detection_support"}'
          headers = {'Content-Type': 'application/json'}
          resp = requests.post(url = gogsURL + "/api/v1/repos/migrate", headers = headers, auth = (gogs_user, gogs_pwd), data = data_repo)  

          if resp.status_code != 200 and resp.status_code != 201:
            print("Error creating git repo (status code: {})".format(resp.status_code))
            print(resp.content)
          else:
            print("Created git repo fraud_detection_support")

          # configure webhook
          data_webhook = '{"type": "gogs", "config": { "url": "' + webhookURL + '", "content_type": "json"}, "events": ["push"], "active": true}'
          headers = {'Content-Type': 'application/json'}
          resp = requests.post(url = gogsURL + "/api/v1/repos/" + gogs_user + "/fraud_detection_support/hooks", 
                              headers = headers, 
                              auth = (gogs_user, gogs_pwd), 
                              data = data_webhook) 

          if resp.status_code != 200 and resp.status_code != 201:
            print("Error configuring the webhook (status code: {})".format(resp.status_code))
            print(resp.content)
          else:
            print("Configured webhook: " + webhookURL)

